"""Inspection catalog mirror — Python constants derived from the canonical TypeScript source.

Canonical source of truth:
    wheelbase-app/frontend/src/lib/inspection-catalog.v2.ts

These constants must be kept in sync with that file whenever step IDs, item IDs,
or question/confidence vocabulary changes. They are used by the agent-side
render-tool payload validator to reject malformed or stale inspection data before
it reaches the frontend.
"""

from __future__ import annotations

# ---------------------------------------------------------------------------
# Step IDs (9 steps, ordered)
# ---------------------------------------------------------------------------

VALID_STEP_IDS: frozenset[str] = frozenset({
    "identity",
    "road",
    "underhood",
    "exterior",
    "interior",
    "tires",
    "brakes",
    "underbody",
    "summary",
})

# ---------------------------------------------------------------------------
# Item IDs (106 items, one per catalog row)
# Generated by replicating the toSlug + collision-resolution logic in
# inspection-catalog.v2.ts §buildGroup.
# ---------------------------------------------------------------------------

VALID_ITEM_IDS: frozenset[str] = frozenset({
    # --- identity ---
    "identity_vin_plate_label_verified",
    "identity_odometer_reading_and_status",
    "identity_stock_number_and_location",
    "identity_title_registration_flags",
    "identity_keys_fobs_manuals_spare_jack",
    "identity_front_and_rear_3_4_photos",
    "identity_vin_odometer_dash_interior_overview",
    "identity_visible_damage_walkaround",
    # --- road ---
    "road_cold_start_and_idle_quality",
    "road_acceleration_and_shift_quality",
    "road_steering_pull_vibration_noise",
    "road_brake_feel_and_stopping_behavior",
    "road_hvac_road_behavior",
    "road_mil_ses_status",
    "road_abs_traction_stability_lights",
    "road_srs_airbag_light",
    "road_tpms_light_and_sensor_state",
    "road_readiness_monitors",
    "road_horn",
    "road_seatbelts_and_airbag_covers",
    "road_windshield_visibility",
    "road_wipers_and_washer_operation",
    # --- underhood ---
    "underhood_engine_condition_abnormal_noise",
    "underhood_battery_terminals_and_hold_down",
    "underhood_charging_system_alternator",
    "underhood_starting_system",
    "underhood_fuel_pump_injectors",
    "underhood_engine_oil_and_filter",
    "underhood_transmission_fluid",
    "underhood_brake_fluid",
    "underhood_power_steering_fluid",
    "underhood_engine_air_and_cabin_filters",
    "underhood_radiator_heater_core_hoses",
    "underhood_coolant_condition_and_level",
    "underhood_water_pump",
    "underhood_electric_fans_fan_clutch",
    "underhood_visible_fluid_leaks",
    # --- exterior ---
    "exterior_panel_damage_dents",
    "exterior_paint_scratches_chips_clear_coat",
    "exterior_rust_corrosion",
    "exterior_prior_repair_evidence",
    "exterior_windshield_glass_cracks",
    "exterior_mirrors_and_housings",
    "exterior_wiper_blades_and_washer_nozzles",
    "exterior_headlights_and_high_beams",
    "exterior_brake_tail_reverse_lights",
    "exterior_turn_signals_and_hazards",
    "exterior_fog_lights_and_marker_lights",
    "exterior_trim_moldings_seals_roof_rack_bed_liner",
    # --- interior ---
    "interior_odor_smoke_water_intrusion",
    "interior_seats_and_upholstery",
    "interior_carpet_headliner_door_panels",
    "interior_dash_console_sun_visors",
    "interior_a_c_operation",
    "interior_heat_operation",
    "interior_windows_locks_mirrors_seats",
    "interior_sunroof_moonroof",
    "interior_infotainment_screen_and_audio",
    "interior_backup_camera_and_parking_sensors",
    "interior_keys_and_fobs",
    "interior_owner_manual_mats_accessories",
    # --- tires ---
    "tires_front_left_tire",
    "tires_front_right_tire",
    "tires_rear_left_tire",
    "tires_rear_right_tire",
    "tires_tire_size_and_brand_match",
    "tires_dry_rot_sidewall_puncture",
    "tires_wheel_damage_missing_lugs_tpms",
    "tires_alignment_concern",
    # --- brakes ---
    "brakes_front_pads",
    "brakes_front_rotors",
    "brakes_front_calipers_and_hardware",
    "brakes_front_brake_lines_hoses",
    "brakes_rear_pads_shoes",
    "brakes_rear_rotors_drums",
    "brakes_rear_calipers_and_hardware",
    "brakes_rear_brake_lines_hoses",
    "brakes_parking_brake",
    "brakes_brake_master_cylinder",
    "brakes_abs_function_warning_state",
    # --- underbody ---
    "underbody_front_struts_shocks",
    "underbody_rear_struts_shocks",
    "underbody_ball_joints_and_control_arms",
    "underbody_tie_rods_and_steering_rack",
    "underbody_sway_bars_end_links_bushings",
    "underbody_wheel_bearings",
    "underbody_frame_unibody_damage",
    "underbody_undercarriage_rust",
    "underbody_exhaust_system",
    "underbody_fluid_leaks_by_source",
    "underbody_transmission_mount_engine_mounts",
    "underbody_cv_axles_boots_u_joints",
    "underbody_transfer_case",
    "underbody_differential_condition",
    # --- summary ---
    "summary_mechanical_grade",
    "summary_safety_inspection_status",
    "summary_emissions_readiness_status",
    "summary_tire_status_headline",
    "summary_warning_light_headline",
    "summary_generated_mechanical_tasks",
    "summary_generated_body_interior_detail_tasks",
    "summary_work_order_estimate",
    "summary_manager_override",
    "summary_inspector_signature",
    "summary_required_photo_slots_complete",
    "summary_report_snapshot_generated",
})

# ---------------------------------------------------------------------------
# Question / answer vocabulary
# ---------------------------------------------------------------------------

QUESTION_TYPES: frozenset[str] = frozenset({
    "multiple_choice",
    "multi_select",
    "free_response",
    "yes_no",
    "measurement",
    "checklist",
})

CONFIDENCE_LEVELS: frozenset[str] = frozenset({
    "low",
    "medium",
    "high",
})
